CREATE TABLE IF NOT EXISTS Book (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  isbn VARCHAR(250) NOT NULL UNIQUE,
  title VARCHAR(500) NOT NULL,
  author VARCHAR(250) NOT NULL,
  price DOUBLE NOT NULL,
  quantity INT DEFAULT 0 CHECK (quantity > -1)
);
 
CREATE TABLE IF NOT EXISTS BookOrderDetails (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  bookId INT NOT NULL,
  quantity INT NOT NULL,
  userId INT DEFAULT 1,
  purchaseTime DATE DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (bookId) REFERENCES Book(id)
);
